#! /bin/bash

echo "Deploying site ..."

changes=`git diff`

if [ ! -z "$changes" ]; then
  echo "You need to commit the changes before proceeding. "
  exit
fi

keybase fs rm /keybase/public/alvarob/index.html
keybase fs cp app/index.html /keybase/public/alvarob/index.html

aws s3 sync app s3://alvarobg.com --acl public-read

echo "Done."
