#!/usr/bin/env bash

echo "Deploying site ..."

changes="$(git diff)"

if [ ! -z "$changes" ]; then
    echo "You need to commit the changes before proceeding. "
    exit
fi

echo "deploying to keybase ..."
keybase fs rm /keybase/public/alvarob/index.html
keybase fs cp app/index.html /keybase/public/alvarob/index.html

echo "deploying contents to S3  ..."
aws s3 sync app s3://alvarobg.com --acl public-read

echo "Invalidating cloudfront cache ..."
aws cloudfront create-invalidation --distribution-id "$ALVAROBGWEB_DISTRO_ID" \
--paths "/*"

echo "Done."
